### PR TITLE
Add zendesk API "paging"

### PR DESCRIPTION
**Pull request by kennyballou**
This changeset teaches the `zendex` API how to auto read the "next_page" of ticket and user results.

This is a _major_ refactor. Chiefly, the unit tests are now using `:exvcr`, the choice of "http client" is now made for the user.

There is small dip in test coverage, looks like a guard clause and case condition aren't "tested". It would take more time than I personally think reasonable to put these two lines fully under test.

Similarly, there is a number of introduced dialyzer warnings because of the heavy usage of `:httpoison.base`. I will need someone who knows more of the black magic art of typespecs to fix those...

### CODE REVIEW

**Comment by kennyballou** [comment]
@shdblowers: Is it necessary to add coverage for the 2 missing lines in the new `lib/zendex.ex` file?

**Comment by shdblowers** [comment]
hi @kennyballou , thanks for putting in the time to do this. as you said it is a _major_ refactor, so will need some time to go over it all.

first glance looks good, I was worrying about how I currently do tests as sticking loads of behaviour in that in memory representation doesn't scale well. thanks again for doing this.

**Comment by kennyballou** [comment]
If there's one thing I would want to improve with this would be to improve the shape of the returned object when including pages. Currently, it's returning a list of "pages", when really, the output of getting pages should be no different from the current output. I may work on that when I get a chance.

**Review by shdblowers — CHANGES_REQUESTED** [review]
I can't merge the code in its current state because of two reasons.

Firstly, documentation has not been updated to match changes. It has either not been touched or just been deleted.

Secondly, there is too much being changed. I like the changes gone into this code review, but they are not related to one another. The more that is changed the more risk there is, I prefer small and safe merges.

Thanks again for your efforts.

**Comment by kennyballou** [comment]
These are all fair points, thank you. I will close this and try to break these changes up.

**Pull request closed without merging**
